CrimeAnalysis/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('RegisterCrime.html/', views.registerCrime, name='registercrime'),
    path('addcrime/', views.addcrime, name='addcrime'),
    path('index.html/', views.index, name='index'),
    path('SearchCrime.html/', views.searchcrime, name='searchcrime'),
    path('UpdateCrime.html/', views.updatecrime, name='updatecrime'),
    path('searchcrime/', views.searchc, name='searchc'),
    path('ShowCrime.html/', views.show, name="show"),
    path('register.html/', views.register, name="registeruser"),
    path('login.html/', views.login, name="loginu"),
    path('updateuser.html/', views.updateuser, name="updateuser"),
    path('viewuser.html/', views.viewusers, name="viewusers"),
    path('chartjs.html/', views.chartjs, name="chartjs"),
    path('ViewCharts.html/', views.ViewCharts, name="ViewCharts"),
    # path('basic-table.html/', views.basictable, name="basictable"),
    path('viewcriminal.html/', views.viewcriminals, name="viewcriminal"),
    path('criminaldetail.html/', views.criminaldetail, name="criminaldetail"),
    path('showupdate_combined/', views.showupdate_combined, name='showupdate_combined'),
    path('UpdateCrime.html/<str:parameter>', views.updatecrime, name='updatecrime'),
    #path('showupdatecrime.html/', views.showcriminaldata, name='showcriminaldata'),
    path('showupdate/<str:param1>/<str:param2>/<str:param3>/', views.showupdate, name='showupdate'),
    path('showcrimedata/', views.showcrimedata, name='showcrimedata'),
    path('deletecrimedata/', views.deletecrimedata, name='deletecrimedata'),
    path('displaycrime/<str:param1>/', views.displaycrime, name='displaycrime'),
    path('displaycrime/', views.displaycrime, name='displaycrime'),
    # path('predicthotspot/', views.predicthotspot, name='predicthotspot'),
    path('searchchart.html/', views.searchchart, name='searchchart'),
    path('searchchartresult.html/', views.searchchartresult, name='searchchartresult'),
    path('welcomeMsg.html/', views.welcomeMsg, name='welcomeMsg'),
    # path('predicthotspotcall/', views.predicthotspotcall, name='predicthotspotcall'),
    path('searchcrimeresult.html/', views.searchcrimeresult, name='searchcrimeresult'),
    path('readFromVoiceSeparate/<str:param>/', views.readFromVoiceSeparate, name='readFromVoiceSeparate'),
    path('statuschangedata/', views.statuschangedata, name='statuschangedata'),
    path('statuschangedata/displaycrime/<int:param1>/', views.displaycrime, name='displaycrime'),
    path('futurehotspots.html/', views.futurehotspots, name='futurehotspots'),    
    path('predicthotspots_of_date/', views.predicthotspots_of_date, name='predicthotspots_of_date'),
    path('sampleurl/', views.sampleurl, name='sampleurl'),
    path('get_police_station/', views.get_police_station, name='get_police_station'),
    path('samplepage.html/', views.get_police_station, name='get_police_station'),
    path('predicthotspot/', views.predictHotspotsLatest, name='predictHotspotsLatest'),
    
    
    
   # path('UpdateCrime.html/showupdatecrime.html/<str:param1>/<str:param2>/<str:param3>/', views.showupdate, name="showupdate"),
]

main/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField

class FormWithCaptcha(forms.Form):
    captcha = ReCaptchaField()

main/views.py
from django.shortcuts import render, redirect
from .models import CrimeOperations
from .models import UserOperations
from django.contrib.auth.decorators import login_required
import json
import re
import joblib
from django.conf import settings
import os
from django.http import HttpResponse
import pyttsx3
import speech_recognition as sr
from time import sleep
import pymongo
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
import numpy as np    
from datetime import datetime
from django.http import JsonResponse
from sklearn.metrics import mean_squared_error
from collections import Counter
import threading
from datetime import datetime, timedelta
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from .forms import FormWithCaptcha
from django.shortcuts import render, redirect




def speak(Text):
    engine = pyttsx3.init("sapi5")
    voices = engine.getProperty('voices')
    engine.setProperty('voice', voices[0].id)
    engine.setProperty('rate', 170)
    print("")
    print(f"You : {Text}.")
    print("")
    engine.say(Text)
    engine.runAndWait()

def speechrecognition(text):
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening.....")
        speak(text)
        print(text)
        r.pause_threshold = 1
        audio = r.listen(source,0,8)

    try:
        print("Recognizing....")
        speak("Recognizing.....")
        query = r.recognize_google(audio,language="en")

        print(f"==> Vedant : {query}")
            
         
        if "skip" in query:
            return "skip"
        
        if "blank" in query or "empty" in query:
            return ""        
            
        if "exit" in query:
            return "terminate"
            
        return query.upper()
    except:
        speak("Dose Not Recognized Properly, Please Repeat Again.....")
        speechrecognition(text)

def readFromVoiceSeparate1(request):
    data = {}
    speak("Welcome Sir, I am Sarthi")
    sleep(0.5)
    speak("Your Voice Assistant")
    sleep(0.5)
    speak("Please tell me following details...")
    txt = speechrecognition("Listeneing for First Name")
    data['fname'] = txt
    txt = speechrecognition("Listeneing for Last Name")
    data['lname'] = txt
    try:
            
        txt = speechrecognition("Listeneing for Age")
        data['age'] = txt
    except:
        print("invalid age..")
    txt = speechrecognition("Listeneing for Date of Birth")
    data['dob'] = txt
    txt = speechrecognition("Listeneing for Gender")
    data['gender'] = txt
    try:
        txt = speechrecognition("Listeneing for Phone Number")
        txt = txt.replace(" ", "")
        if len(txt) < 10:
            need = 10-len(txt)
            txt = txt[:len(txt)]+"0"*need
        elif len(txt) > 10:
            txt = txt[:9]
        
    except:
        print("invalid phone number")
    data['phone'] = txt
    txt = speechrecognition("Listeneing for Height")
    data['height'] = txt
    txt = speechrecognition("Listeneing for Address")
    data['addrs'] = txt
    txt = speechrecognition("Listeneing for FIR Number")
    data['FIR_No'] = txt
    txt = speechrecognition("Listeneing for Type of Crime")
    data['Type_of_Crime'] = txt
    txt = speechrecognition("Listeneing for Number of Person Involve")
    data['Number_Of_Person_Involve'] = txt
    txt = speechrecognition("Listeneing for Weapons use for Crime")
    data['Weapons_use_for_Crime'] = txt
    txt = speechrecognition("Listeneing for Date of Crime")
    data['Date_of_Crime'] = txt
    txt = speechrecognition("Listeneing for Time Period of Crime")
    data['Time_Period_of_Crime'] = txt
    txt = speechrecognition("Listeneing for Vehicle Used")
    data['Vehicle_use'] = txt
    txt = speechrecognition("Listeneing for Vehicle Number")
    data['Vehicle_No'] = txt
     

    return data


def readFromVoiceSeparate(request,param):
    data = {}
    
    txt = speechrecognition("Listeneing for "+param)
    if txt == None:
        txt = ""

    if "Phone" in param or "Age" in param or "Aadhar-Number" in param or "Height" in param or "F-I-R-Number" in param or "Number-Of-Person-Involved" in param:
        txt = txt.replace(" ", "")
        txt = re.findall(r'\d+', txt)

        # Convert the list of strings to a list of integers
        txt = [int(num) for num in txt]
        
    
    print("PARAM:- ",param)
    print("VALUE:- ",txt)

    data['query'] = txt

    return JsonResponse(data)

def readDescriptionFromVoice(request):
    data={}
    stat={}
    text = ""
    text_predict = ""
    if request.POST.get('submitbtn'):
        text_predict = request.POST.get('crime_description')
        text = text_predict
        print("text = ",text)
    else:
        text = speechrecognition("Listening For Crime Description")
        text_predict = text
    # Load the pre-trained model
    svm_type_classifier, tfidf_vectorizer = joblib.load('C:/CrimeAnalysis_ML/trained_model.joblib')
    def classify_description(description):
        tfidf_new = tfidf_vectorizer.transform([description])
        predicted_type = svm_type_classifier.predict(tfidf_new)[0]
        return predicted_type
    def preprocess(text):
        text = re.sub(r'[^\w\s\']',' ',text)
        text = re.sub(r' +',' ',text)
        return text.strip().lower()
    # text_predict = """In a quiet suburban neighborhood, a daring burglary unfolded under the cover of darkness. A skilled thief, equipped with tools of the trade, discreetly 
    # entered a residence through an unlocked back door. Moving with calculated precision, the intruder swiftly ransacked the home, absconding with valuable jewelry and electronic devices.
    # The residents, unaware of the intrusion until morning, were left shocked and violated by the audacious crime that had taken place within the sanctity of their own home. 
    # Law enforcement was promptly notified, initiating an investigation into the burglary that left the community on edge."""
    text_predict = preprocess(text_predict)
    text_predict = text_predict.replace("\n", " ")
    # text_predict = "attempted to murder a woman from a car driver"
    predicted_type = classify_description(text_predict)
    # Display the predicted Category and Type
    
    predicted_type = predicted_type.upper()
    data['type'] = predicted_type
    
    print(f"Predicted Type: {predicted_type}")
    ####################Crime Description Data Extraction
    import spacy
    nlp = spacy.load("en_core_web_sm")
    # text = """In the quiet neighborhood of Maple Street, a heinous crime occurred. The suspect, John Doe, a 35 year old male with a date of birth on 4/15/1987, was involved in an armed robbery. The crime took place on 7/12/2023 between 2 PM and 4 PM.
    # The suspect, armed with a firearm, robbed a convenience store at 123 Elm Street. The FIR number for the case is FIR-2023-567. Two other individuals were part of the crime, one wielding a knife and the other acting as the getaway driver.
    # The getaway vehicle, a red sedan with license plate number ABC-123, had three people inside. The driver was a tall man of 165cm (5'5"), wearing a black cap and sunglasses. The passenger in the front seat was a woman with a blue scarf, and in the back seat, there was a man in a green jacket.
    # The crime spot was near a prominent landmark, the city park. The pincode for the area is 567896. The incident was captured on CCTV cameras, and the police are actively investigating. The latitude and longitude of the crime spot are 40.7128 N and 74.0060 West.  Phone Number is 9922334455
    # """
    # text = "Rajesh Kumar attempted to murder Pravin"
    import string
    def remove_punctuation(text):
        # Define a translation table that excludes periods (full stops)
        translator = str.maketrans('', '', string.punctuation.replace('.', ''))
        
        # Apply the translation to the text
        text = text.translate(translator)
        
        return text
    # Example usage:
    text_with_punctuation = text
    text = remove_punctuation(text_with_punctuation)
    # print("text = ",text) 
    doc = nlp(text)
    
    
    pattern = r'\d+'
    names = []
    
    first_name = ""
    last_name = ""
    # for ent in doc.ents:
    #     if ent.label_ == "PERSON":
    #         match = re.search(pattern, ent.text)
    #         if not match:
    #             print("entities: ",ent.text)
    
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            match = re.search(pattern, ent.text)
            if not match:
                name_parts = ent.text.split()
                if len(name_parts) > 1:
                    first_name = name_parts[0]
                    last_name = " ".join(name_parts[1:])
                    names.append((first_name, last_name))
    print("Names extracted (First Name, Last Name):")
    for first_name, last_name in names:
        print("First Name: "+first_name)
        print("Last Name: "+last_name)
    #
    data['fname'] = first_name
    data['lname'] = last_name
    age = None
    for ent in doc.ents:
        if ent.label_ == "DATE" or ent.label_ == "CARDINAL":
            if "Age" in ent.text or "age" in ent.text or "year" in ent.text or "years" in ent.text or "old" in ent.text or "years-old" in ent.text or "year-old" in ent.text:
                pattern = r'\d+'
                numbers = re.findall(pattern, ent.text)
                    
                for number in numbers:
                    # print(number)
                    age = number
            else:
                pattern = r'\d+'
                numbers = re.findall(pattern, ent.text)
                for number in numbers:
                    age = number          

    print("age=",age)
    
    #

main/templates/SearchResult.html
{%load static%} {%block content%}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>CrimeAnalysis</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css'%}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}" />

  <link rel="stylesheet" href="{% static 'assets/css/style.css'%}" />
  <!-- End layout styles -->
    
  <!-- MyStyle css -->
  <link rel="stylesheet" href="{% static 'assets/css/mystyle.css'%}" />

</head>

<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    {% include 'components/navbar.html' %}


    <!-- partial -->
    <div class="container-fluid page-body-wrapper" style="height: 100vh">
      <!-- partial:partials/_sidebar.html -->
      {% include 'components/sidebar.html' %}

      <!-- partial -->
      <div class="main-panel main-div">
        {%if msg%}
        <div class="alert alert-success alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{msg}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {%if err%}
        <div class="alert alert-danger alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{err}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}

        <div class="content-wrapper">
            <form method="post">{% csrf_token %}
            <div class="d-flex justify-content-between align-items-center mt-3">
                <Button style="width: auto;text-align: left;border: none;"><a class="btn btn-block btn-gradient-primary " href="/viewcriminal.html/">Go to View Criminals</a></Button>
                {% comment %} <h1 class="h2">Criminal and Crime Details</h1> {% endcomment %}
                <div class="btn-toolbar mb-2 mb-md-0">
                    {% comment %} <button class="border-0 "><a href="/showcrimedata/" class="btn btn-primary mx-1">Update</a></button>
                    <button class="border-0 "><a href="/showcrimedata/" class="btn btn-primary mx-1">Delete</a></button> {% endcomment %}
                    <input type="hidden" name="firno" value="{{ data.FIR_No }}">
            
                    <button type="submit" class="btn btn-primary mx-1" name="updatebtn" formaction="{% url 'main:showcrimedata'%}">UPDATE</button>
                    <button type="submit" class="btn btn-danger mx-1" name="crimebtn" formaction="{% url 'main:deletecrimedata'%}" onclick="return confirmDelete()">DELETE</button>

                  
                    
          
                </div>
            </div>
           

            <div class="row mt-4">
                <div class="col-lg-5">
                    <!-- Criminal Details -->
                    <div class="card bg-white shadow mb-4">
                        <div class="card-header bg-primary text-white">
                            <h5 class="mb-0">Criminal Details</h5>
                        </div>
                        <div class="card-body text-center">
                            <img src="{% static 'assets\images\faces\criminal_profile.png' %}" class="img-fluid rounded-circle mb-3" alt="Criminal Image" width="150" height="150">
                            <h4 class="card-title">{{ data.First_Name }} {{ data.Last_Name }}</h4>
                            <p class="card-text"><strong>Age</strong> {{ data.Age }} years old</p>
                            <p class="card-text"><strong>Gender</strong> {{ data.Gender }}</p>
                            <p class="card-text"><strong>Height</strong> {{ data.Height }}</p>
                            <p class="card-text"><strong>Address</strong> {{ data.Address }}</p>
                            <p class="card-text"><strong>Pincode</strong> {{ data.Pincode }}</p>
                            <p class="card-text"><strong>Phone_No</strong> {{ data.Phone_No }}</p>
                            <!-- Add more details as needed -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-7">
                    <!-- Crime Details -->
                    <div class="card bg-white shadow mb-4">
                        <div class="card-header bg-danger text-white">
                            <h5 class="mb-0">Crime Details</h5>
                        </div>
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><strong>FIR No.:</strong> {{ data.FIR_No }}</li>
                                <li class="list-group-item"><strong>Vehicle No.:</strong> {{ data.Vehicle_No }}</li>
                                <li class="list-group-item"><strong>Number of Person Involve:</strong> {{ data.Number_Of_Person_Involve }}</li>
                                <li class="list-group-item"><strong>Type of Crime:</strong> {{ data.Type_of_Crime }}</li>
                                <li class="list-group-item"><strong>Weapon use for Crime:</strong> {{ data.Weapons_use_for_Crime }}</li>
                                <li class="list-group-item"><strong>Vehicle Use:</strong> {{ data.Vehicle_use }}</li>
                                <li class="list-group-item"><strong>Discription of Person sitting on Vehicle:</strong> {{ data.Discription_of_Person_sitting_on_Vehicle }}</li>
                                <li class="list-group-item"><strong>Discription of Vehicle:</strong> {{ data.Discription_of_Vehicle }}</li>
                                <li class="list-group-item"><strong>Crime Spot:</strong> {{ data.Crime_Spot }}</li>
                                <li class="list-group-item"><strong>Number of Person on Vehicle:</strong> {{ data.No_of_Person_on_Vehicle }}</li>
                                <li class="list-group-item"><strong>Police Station</strong> {{ data.Police_Station }}</li>
                                <!-- Add more crime details as needed -->
                                <input type="hidden" name="firno" value="{{ data.FIR_No }}">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-lg-12">
                    <!-- Additional Details -->
                    <div class="card bg-white shadow mb-4">
                        <div class="card-header bg-info text-white">
                            <h5 class="mb-0">Additional Details</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <p><strong>Date of Birth:</strong> {{ data.Date_of_Birth }}</p>
                                    <p><strong>Aadhar Number:</strong> {{ data.Aadhar_No|floatformat:0 }}</p>
                                    <p><strong>Latitude:</strong> {{ data.Latitude }}</p>
                                    <p><strong>Discription of Crime Spot:</strong> {{ data.Discription_of_Crime_Spot }}</p>
                                    <!-- Add more personal details as needed -->
                                </div>
                                <div class="col-md-6">
                                    <p><strong>Date of Crime:</strong> {{ data.Date_of_Crime }}</p>
                                    <p><strong>Time Period of Crime:</strong> {{ data.Time_Period_of_Crime }}</p>
                                    <p><strong>Longitude:</strong> {{ data.Longitude }}</p>
                                    <p><strong>Weapons use for Crime:</strong> {{ data.Weapons_use_for_Crime }}</p>
                                    <!-- Add more crime-related details as needed -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-lg-12">
                    <!-- Status and Actions -->
                    <div class="card bg-white shadow mb-4">
                        <div class="card-header bg-success text-white">
                            <h5 class="mb-0">Status</h5>
                        </div>
                        <div class="card-body text-center">
                  
                            
                            {% if data.Status == "Not Detected" %}
                            <span class="badge rounded-pill bg-danger text-white fs-4 fw-bold">{{ data.Status }}</span>Update to  :
                            <input type="submit" class="btn btn-danger mx-1" name="status_changed" formaction="{% url 'main:statuschangedata'%}" value="Detected"/>

                            {% else %}
                            <span class="badge rounded-pill bg-success text-white fs-4 fw-bold">{{ data.Status }}</span>Update to  :
                            <input type="submit" class="btn btn-danger mx-1" name="status_changed" formaction="{% url 'main:statuschangedata'%}" value="Not Detected"/>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js'%}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'assets/vendors/chart.js/Chart.min.js'%}"></script>
  <script src="{% static 'assets/js/jquery.cookie.js'%}" type="text/javascript"></script>
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js'%}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js'%}"></script>
  <script src="{% static 'assets/js/misc.js'%}"></script>
  <!-- endinject -->
  <!-- Custom js for this page -->
  <script src="{% static 'assets/js/dashboard.js'%}"></script>
  <script src="{% static 'assets/js/todolist.js'%}"></script>
  
  <!--JS for basic tasks-->
  <script src="{% static 'assets/js/myjs.js'%}"></script>
  <script>
    function confirmDelete() {
        // Display a confirmation dialog
        var result = confirm("Are you sure you want to delete this record?");
    
        // If the user clicks "OK", the result will be true; otherwise, it will be false
        return result;
    }
    </script>
  
  <!-- End custom js for this page -->
</div>
  
</body>

</html>

{%endblock%}

main/templates/UpdateCrime.html
{%load static%} {%block content%}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>CrimeAnalysis</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css'%}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css'%}" />
  <!-- endinject -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css'%}" />
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico'%}" />
    <!-- MyStyle css -->
    <link rel="stylesheet" href="{% static 'assets/css/mystyle.css'%}" />


</head>

<body class="bg-white ">
  <div class="container-scroller bg-white ">
      {% include 'components/navbar.html' %}


    <!-- partial -->
    <div class="container-fluid page-body-wrapper" style="height: 100vh">
      <!-- partial:partials/_sidebar.html -->
      {% include 'components/sidebar.html' %}
      <!-- partial -->
      <div class="main-panel main-div bg-white">
        {%if msg%}
        <div class="text-center alert alert-success alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{msg}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {%if err%}
        <div class="text-center alert alert-danger alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{err}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
            <div class="content-wrapper d-flex align-items-center auth p-0" style="background-color:white !important;">
              
              <div class="row flex-grow bg-white">
                <div class=" mx-auto bg-white">
                  <div class="auth-form-light text-left py-1 bg-white ">
                    
                    <div class="brand-logo mt-4" style="text-align:center;">
                      {% comment %} <img src="{%static 'assets/images/logo.svg' %}"> {% endcomment %}
                      <h1>Select Crime to Update Record</h1>
    
                    </div>
                    <!-- <h6 class="font-weight-light">Signing up is easy. It only takes a few steps</h6> -->
                    
                    <div class="col-lg-8 col-10 m-auto">
                      <form action="/criminaldetail.html/" method="post">{% csrf_token %}
                        <table class="" style="" id="view_users">
                          <tr class="" style="border-bottom: 1px solid #36454F;">
                            <th class="p-2 pe-4 col-2  ">First Name</th>
                            <th class="p-2 pe-4 col-2  ">Last Name</th>
                            <th class="p-2 pe-4 col-2  ">Crime</th>                           
                          </tr>
                          {% for criminal in criminals_data %}
                          <tr class="" style="border-bottom: 1px solid #9b9b9b;">
                              <td class="p-2 pe-4 col-2">{{ criminal.first_name }}</td>
                              <td class="p-2 pe-4 col-2">{{ criminal.last_name }}</td>
                              <td class="p-2 pe-4 col-2">
                                {% for crime_type in criminal.crime_types %}
                                    <a href="{% url 'main:showupdate' param1=criminal.first_name param2=criminal.last_name param3=crime_type %}">
                                        {{ crime_type }}<br>
                                    </a>
                                {% endfor %}
                            </td>
                              
                          </tr>
                      {% endfor %}

                        </table>
                      </form> 
                    </div>
                        
                  </div>
                </div>
            <!-- content-wrapper ends -->
            </div>
            
          <!-- page-body-wrapper ends -->
        </div>
    
          
        
        <footer class="footer">
          <div class="container-fluid d-flex justify-content-between">
            <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © </span>
            <span class="float-none float-sm-end mt-1 mt-sm-0 text-end">
              Free
            </span>
          </div>
        </footer>
      </div>
    </div>
    <!-- partial -->
  </div>



  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js'%}"></script>

  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js'%}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js'%}"></script>
  <script src="{% static 'assets/js/misc.js'%}"></script>
  <!-- endinject -->
  <!-- Custom js for this page -->
  <script src="{% static 'assets/js/file-upload.js'%}"></script>
  <script src="{% static 'assets/js/myjs.js'%}"></script>
  <!-- End custom js for this page -->
</div>
</body>

</html>
{%endblock%}

main/templates/sampleurl.html
sampleurl.html page